/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasAreaRouteImport } from './routes/vagas.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasAreaRoute = VagasAreaRouteImport.update({
  id: '/vagas/$area',
  path: '/vagas/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vagas/$area': typeof VagasAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vagas/$area': typeof VagasAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vagas/$area': typeof VagasAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vagas/$area'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vagas/$area'
  id: '__root__' | '/' | '/vagas/$area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VagasAreaRoute: typeof VagasAreaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$area': {
      id: '/vagas/$area'
      path: '/vagas/$area'
      fullPath: '/vagas/$area'
      preLoaderRoute: typeof VagasAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VagasAreaRoute: VagasAreaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
